character:
  roles:
    - dps
    - tank
    - healer
  weapons:
    - crossbow
    - dagger
    - greatsword
    - longbow
    - staff
    - sword_and_shield
    - wand
    - spear
  klasses:
    scorpion:
      main_weapon: crossbow
      offhand: dagger
    outrider:
      main_weapon: crossbow
      offhand: greatsword
    scout:
      main_weapon: crossbow
      offhand: longbow
    cavalier:
      main_weapon: crossbow
      offhand: spear
    battleweaver:
      main_weapon: crossbow
      offhand: staff
    raider:
      main_weapon: crossbow
      offhand: sword_and_shield
    fury:
      main_weapon: crossbow
      offhand: wand
    ravenger:
      main_weapon: dagger
      offhand: greatsword
    infiltrator:
      main_weapon: dagger
      offhand: longbow
    shadowdancer:
      main_weapon: dagger
      offhand: spear
    spellblade:
      main_weapon: dagger
      offhand: staff
    berserker:
      main_weapon: dagger
      offhand: sword_and_shield
    darkblighter:
      main_weapon: dagger
      offhand: wand
    sentinel:
      main_weapon: greatsword
      offhand: staff
    ranger:
      main_weapon: greatsword
      offhand: longbow
    gladiator:
      main_weapon: greatsword
      offhand: spear
    crusader:
      main_weapon: greatsword
      offhand: sword_and_shield
    paladin:
      main_weapon: greatsword
      offhand: wand
    impaler:
      main_weapon: longbow
      offhand: spear
    liberator:
      main_weapon: longbow
      offhand: staff
    warden:
      main_weapon: longbow
      offhand: sword_and_shield
    seeker:
      main_weapon: longbow
      offhand: wand
    eradicator:
      main_weapon: spear
      offhand: staff
    steelheart:
      main_weapon: spear
      offhand: sword_and_shield
    voidlance:
      main_weapon: spear
      offhand: wand
    disciple:
      main_weapon: staff
      offhand: sword_and_shield
    invocator:
      main_weapon: staff
      offhand: wand
    templar:
      main_weapon: sword_and_shield
      offhand: wand